---
- name: iOS Show Commands
  hosts: switch
  gather_facts: false

  tasks:
    - name: show version and capture in variable
      ios_command:
        commands:
         - show version
      register:
        ios_command_output
    - debug:
        var: ios_command_output